"""
Alembic environment.

The URL comes from `DATABASE_URL` via `envConfig`, never from alembic.ini, so a
production credential is never a committed string.

Migration policy (§9 of the sprint plan): one revision per logical change, and
every autogenerated revision is hand-reviewed before it merges. Autogenerate does
not emit PostGIS GiST indexes on `geom`, and it will happily type a money column
as `Float`. Both are caught by review, and the money-column case is a blocking
CI check from S2.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.ext.asyncio import async_engine_from_config

# Models register themselves on Base's metadata by being imported. S2 adds the
# first of them (firms, users, jobs).
import app.models  # noqa: F401
from alembic import context
from app.configs.dbConfig import Base
from app.configs.envConfig import settings

config = context.config
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _include_object(obj, name, type_, reflected, compare_to):
    # PostGIS keeps its own bookkeeping tables in the same schema; they are not ours.
    if type_ == "table" and name in {"spatial_ref_sys", "geography_columns", "geometry_columns"}:
        return False
    return True


def run_migrations_offline() -> None:
    context.configure(
        url=settings.DATABASE_URL,
        target_metadata=target_metadata,
        literal_binds=True,
        compare_type=True,
        include_object=_include_object,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def _do_run_migrations(connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        include_object=_include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    connectable = async_engine_from_config(
        {"sqlalchemy.url": settings.DATABASE_URL},
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(_do_run_migrations)
    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
