export const ROUTES = {
  signin: '/signin',
  dashboard: '/',
  clients: '/clients',
  mandates: '/mandates',
  mandate: (id: string) => `/mandates/${id}`,
  properties: '/properties',
  property: (id: string) => `/properties/${id}`,
  comparables: (propertyId: string) => `/properties/${propertyId}/comparables`,
  valuations: (propertyId: string) => `/properties/${propertyId}/valuations`,
  documents: (propertyId: string) => `/properties/${propertyId}/documents`,
  leases: (propertyId: string) => `/properties/${propertyId}/leases`,
  construction: (propertyId: string) => `/properties/${propertyId}/construction`,
  rera: '/rera',
  deliverables: '/deliverables',
  deliverable: (id: string) => `/deliverables/${id}`,
  review: (deliverableId: string) => `/deliverables/${deliverableId}/review`,
  usage: '/usage',
} as const;
